#include "copyright.h"

/*===========================================================*
 * error_msg.h - Error Handlers.
 *
 * Description:
 *  This file provides standard interface for error messages
 *  that are generated by the clipocv package.
 *  The error massage handler it self is environment dependent
 *  and it is provided outside the clipocv package.
 *
 *===========================================================*/

#pragma once
#ifndef ERROR_MSG
#define ERROR_MSG

// TODO these error may not be relevant in ClipOCV

#define ERR_NONE			0
#define	ERR_PROBE			1
#define ERR_UNKNOWN_FORMAT	        2
#define ERR_READ			3
#define ERR_MALLOC			4
#define ERR_OPEN			5

namespace clipocv {

void error_msg(const char *s, unsigned long a);
void clip_exception(int num);

} // namespace
#endif







